version: '3'
services:
    db:
        image: mysql
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: my_secret_password
            MYSQL_DATABASE: traffic_limits
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
      
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8081:80
       
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        ports:
            - 2181:2181
        environment:
            ALLOW_ANONYMOUS_LOGIN: "yes"
            
        volumes:
            - zoo_data:/bitnami/zookeeper
     
    kafka:
        image: 'bitnami/kafka:latest'
        ports:
          - 9093:9093
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
            ALLOW_PLAINTEXT_LISTENER: "yes"
            KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_CFG_LISTENERS: CLIENT://:9092,EXTERNAL://:9093
            KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka:9092,EXTERNAL://localhost:9093
            KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT

        volumes:
            - kafka_data:/bitnami/kafka
            
        restart: always
            
        depends_on:
          - zookeeper

volumes:
  dbdata:
  zoo_data:
  kafka_data: